# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fam', models.CharField(max_length=40)),
                ('fath', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('interested', models.CharField(max_length=256)),
                ('day', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('time', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Клиенты',
                'verbose_name': 'Клиент',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Статусы заказа',
                'verbose_name': 'Статус заказа',
            },
        ),
        migrations.AddField(
            model_name='myclient',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='landings.Status'),
        ),
    ]
